### ISSUE TITLE
About datasets kitti

### ISSUE THREAD

**Issue by ZYCheng-coder** [qiaozhijian/VCR-Net#3]
Thanks for your work , Where can I get the kitti_h5 data .  Thanks.

**Comment by qiaozhijian** [comment]
Thanks for your attention. I'm sorry that since there is no enough space to put the kitti data set, so I didn't publish it. You can downsample the raw bin and transform it as the paper said. By the way, I delete kitti_h5 because it is downsampled a lot, and I'm working for some methods that can handle with more points.
